### ISSUE TITLE
Create an actor list

### ISSUE THREAD

**Issue by gsufrank** [GSCSCI5530/Angstrom#13]
# Take a look at these Actors please, so we can move forward

**Comment by gsufrank** [comment]
System Administrator
Manager
Cashier
Sales Activity System

**Comment by gsufrank** [comment]
Cashier - process Sales, handle returns, cash in, cash out
Manager - start up, shut down
System Administrator - add users, modify users, delete users, manage security, manage system tables
Sales Activity System - analyze sales and performance data
Inventory Management System - add and modify inventory

**Comment by gsufrank** [comment]
Take a look at these Actors please, so we can move forward

**Comment by cr10989** [comment]
> Owner
> Manager
> Cashier

I second these
