### ISSUE TITLE
Create an Actor-Goal List

### ISSUE THREAD

**Issue by gsufrank** [GSCSCI5530/Angstrom#14]
# Take a look at this Actor-goal list please, so we can move forward

**Comment by gsufrank** [comment]
Cashier - process Sales, handle returns, cash in, cash out
Manager - start up, shut down
System Administrator - add users, modify users, delete users, manage security, manage system tables
Sales Activity System - analyze sales and performance data
Inventory Management System - add and modify inventory

**Comment by cr10989** [comment]
> Cashier - process Sales, handle returns, cash in, cash out
> Manager - start up, shut down
> System Administrator - add users, modify users, delete users, manage security, manage system tables
> Sales Activity System - analyze sales and performance data
> Inventory Management System - add and modify inventory

I don't think Sales Activity System and Inventory Management System should be included here

**Comment by gsufrank** [comment]
No feedback received for too long, making a call and moving forward with the three identified actors and goals Christian helped identify. 

Shop Owner/Owner - add and modify inventory, analyze sales and performance data
Administrator/Manager - add users, modify users, delete users, manage security, manage system tables
Cashier/User - process Sales, handle returns, cash in, cash out

Now the use cases and diagrams need to be developed
